<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <AssemblyName>ParkingSystem.Migrator</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>ParkingSystem.Migrator</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>
  <ItemGroup>
    <None Update="appsettings.json;log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Abp.Castle.Log4Net" Version="10.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ParkingSystem.Core\ParkingSystem.Core.csproj" />
    <ProjectReference Include="..\ParkingSystem.EntityFrameworkCore\ParkingSystem.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>